Milestone 1: Add linters files & Start React Proyect
mdg0410/Math_Magicians pull request #1
Opened 2023-06-09 04:21 UTC by mdg0410

In this milestone: 

- Add Linters files
- Create a project React 
- Configure Linter & React

2023-06-09 04:48 UTC, divinecharlotte requested changes
Hi @mdg0410 ,

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 

- Use of GitHub flow👍 
- Descriptive pr 👍 

 




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

- [ ] kindly consider adding a working link to your license  under your license section to make your readme professional

_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 06:24 UTC, descholar-ceo requested changes
Hi @mdg0410 🤝 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
👍🏽 PR is professional ✔️ 
👍🏽 Added the license file ✔️ 
👍🏽 Linters installed and they are passing ✔️ 
👍🏽 Correct usage of git flow ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] While clicking on the license link in your readme file, we are still getting a 404 page
<img width="1676" alt="Screenshot 2023-06-09 at 08 21 59" src="https://github.com/mdg0410/Math_Magicians/assets/56886064/ad7730ec-2a55-4ac2-8251-dae66a2e0a3a">


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 07:22 UTC, danmainah approved these changes
Hi @mdg0410 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ Professional written README file with all sections required.
✔️ Project created using  Create React App 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 07:22 UTC, danmainah commented on README.md
> +[Project Link][]
- [ ] [optional] @mdg0410 Great work implementing the changes requested, however, I would advise you remove the live demo link since it's not working, it's making the readme look unprofessional, a good readme should always have all the links working. 
- [ ] [optional] Kindly check your spelling, you misspelled the word project, in your branch name and in the pull request title. You can install [grammary extension](https://www.grammarly.com/browser/chrome) which will always notify you when you got a spelling or grammar error.

2023-06-15 14:29 UTC, merged

2023-07-03 20:25 UTC, Qoosim reviewed
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @mdg0410, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._